import Head from "next/head";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Us | Technical Council</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Form Section */}
      <section className="bg-gradient-to-t from-neutral-720 to-neutral-900 p-6 lg:pb-20">
        <div className="container mx-auto flex flex-col lg:flex-row xl:px-24">
          {/* Contact Form */}
          <div className="mx-auto w-full max-w-sm text-white lg:flex-grow-0">
            <h2 className="mb-1 text-4xl font-bold">Reach Out to Us</h2>
            <h3 className="text-lg text-gray-300">
              Fill out the form in case of any query
            </h3>
            <form className="mt-4 font-roboto">
              <label className="form-label" htmlFor="email">
                Email
              </label>
              <input
                className="form-input"
                type="email"
                name="email"
                id="email"
                // placeholder="Enter your email"
                required
              />
              <label className="form-label" htmlFor="phoneNo">
                Phone No.
              </label>
              <input
                className="form-input"
                type="number"
                name="phoneNo"
                id="phoneNo"
                min="10"
                // placeholder="Enter your phone no"
              />
              <label className="form-label" htmlFor="email">
                Query
              </label>
              <textarea
                className="form-input"
                name="query"
                id="query"
                cols="30"
                rows="5"
                // placeholder="Write your query here"
                required
              ></textarea>
              <button
                className="mx-auto mt-4 block bg-neutral-720 px-12 py-2 hover:bg-neutral-750/60 focus:outline-none focus:ring-1 focus:ring-offset-1"
                type="submit"
              >
                Send
              </button>
            </form>
          </div>
          {/* Address */}
          <div className="mt-16 flex w-full flex-col items-center space-y-2.5 lg:mx-auto lg:mt-4 lg:w-auto">
            <img
              className="h-8 w-8"
              src="/assets/svg/map-marker.svg"
              alt="Map Marker"
            />
            <h2 className="text-center text-2xl font-bold text-golden-400 md:text-3xl">
              Address
            </h2>
            <p className="text-center text-gray-200 md:text-xl">
              323, Acad Block 4 <br />
              Indian Institute of Technology Gandhinagar
            </p>
            <img
              className="w-full max-w-sm rounded border-4 border-green-500"
              src="/assets/images/map.jpg"
              alt="Map"
            />
          </div>
        </div>
      </section>
      {/* Social Media */}
      <section className="bg-neutral-720">
        <div className="container mx-auto md:pt-8 lg:pt-0">
          <h3 className="text-center text-lg text-white md:text-[22px]">
            Connect with us
          </h3>
          <div className="flex items-center justify-center space-x-3 pt-2 pb-4 sm:space-x-6 md:mt-2 md:space-x-10">
            <img
              className="h-8 w-8 rounded-full md:h-10 md:w-10"
              src="/assets/icons/facebook-48.png"
              alt="Facebook"
            />
            <img
              className="h-8 w-8 rounded-full md:h-10 md:w-10"
              src="/assets/icons/linkedin-48.png"
              alt="LinkedIn"
            />
            <img
              className="h-8 w-8 rounded-full md:h-10 md:w-10"
              src="/assets/icons/instagram-48.png"
              alt="Instagram"
            />
            <img
              className="h-7 w-7 rounded-full md:h-9 md:w-9"
              src="/assets/icons/google-48.png"
              alt="Google"
            />
          </div>
        </div>
      </section>
    </>
  );
};

export default Contact;
