const CLUBS = [
	{
		id: 0,
		name: "Silent DJ",
		desc: "The Silent DJ event will take place in a dedicated room at Central Arcade. Students will be provided with their own earphones and will be able to stream music through Twitch. The objective of the event is to encourage students to explore the science of sound and music, while also promoting creativity and self-expression.",
		banner: "/assets/ignite/1.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 1,
		name: "URL Human Chain",
		desc: "The Breaking World Record for URL Human Chain event will be a unique opportunity for students to showcase their teamwork and problem-solving skills. The objective of the event is to break the world record for the longest human chain formed by a URL. Students will participate in the event by visiting the website https://students.iitgn.ac.in/tech-council/urlchain and forming a human chain by following the URL redirects. The final redirect will lead them to a lab hunt where they will be able to learn about the various labs at IITGN.",
		banner: "/assets/ignite/2.png",
		backgroundColor: "",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 2,
		name: "NFT Airdrop",
		desc: "The NFT Airdrop event is a great opportunity for students to learn about the world of non-fungible tokens (NFTs) and web3-blockchain technology. NFTs are unique digital assets that are stored on a blockchain and are becoming increasingly popular for digital art, collectables, and more. During the event, students will be able to create their own NFTs using software like Adobe Photoshop and Adobe Illustrator. They will have the opportunity to let their creativity shine by designing unique and personalized NFTs that they can later add to their web3 wallets.",
		banner: "/assets/ignite/3.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 3,
		name: "Tic Tac Toe (4x4)",
		desc: "We will be making a 4x4 Tic Tac Toe game using a field-programmable gate array (FPGA) technology. To achieve this, we will be utilizing a combination of LEDs and breadboards connected to the FPGA as the actual 4x4 matrix. Additionally, we will incorporate buttons to enable players to select their desired LED and make their moves by blinking the corresponding LED on the FPGA. This implementation aims to provide an interactive and engaging gaming experiencewhile demonstrating the capabilities of FPGA technology.",
		banner: "/assets/ignite/4.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
	{
		id: 4,
		name: "Scratch-based game/logic building",
		desc: "An event that can inspire and encourage students to learn programming and game development using the beginner-friendly platform Scratch. The event can be conducted in the form of a workshop followed by a competition, where students can learn the basics of Scratch and then showcase their skills by creating games or programs using the platform.",
		banner: "/assets/ignite/5.png",
		backgroundColor: "#000000",
		date: "April 3, 2023",
		time: "08:00 Hrs",
		venue: "Central Arcade",
	},
];

export default CLUBS;
