import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Events = () => {
  return (
    <>
      <Head>
        <title>Events | Technical Council</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h2>Events</h2>
      </div>
    </>
  );
};

export default Events;
