import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Clubs = () => {
  return (
    <>
      <Head>
        <title>Clubs &amp; Hobby Groups | Technical Council</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-neutral-700  p-6 pt-20 lg:pb-20">
        <div>
          <h1 className="text-center text-white text-4xl ">CLUBS & HOBBY GROUPS</h1>
          <p className="pt-10 pb-5 text-center text-white text-lg leading-loose">The various Technical Clubs along with Tinkerers' Lab coordinate together to take initiatives and conduct activities</p>
          <p className="pb-5 text-center text-white text-lg leading-loose">round the year to further the technical quotient of IITGN and also make a difference to everyone around us.</p> 
          <p className="pb-5 text-center text-white text-lg leading-loose">Wish to join one? Wish to request a workshop or event? Do not hesitate to contact us!</p>
        </div>

        {/* Cards */}
        <div class="grid grid-cols-1 lg:grid-cols-3 px-6 pt-20 lg:gap-x-8 lg:gap-y-4 justify-items-center">
          {/* Cards_1 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded max-w-sm">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4 ">
              <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">MEAN MECHANICS</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6 ">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_1 end */}

          {/* Cards_2 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg ">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">DIGIS</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_2 end */}

          {/* Cards_3 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg ">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">ODYSSEY</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_3 end */}

          {/* Cards_4 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg ">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">METIS</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_4 end */}

          {/* Cards_5 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">ML HOBBY GROUP</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_5 end */}

          {/* Cards_6 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">WEB3/BLOCKCHAIN HOBBY GROUP</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_6 end */}

          {/* Cards_7 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">ESPORTS WING</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_7 end */}

          {/* Cards_8 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">HARDWARE, Iot, VLSI GROUP</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_8 end */}

          {/* Cards_9 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4">
            <div class="text-green-700 text-xl mb-2 hover:scale-105 ease-in duration-200">
                <a href="#" class="">ANVESHANAM</a>
              </div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            <div className="flex items-left justify-left space-x-3 pt-1 pb-4 px-6">
						<a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/google-48.png"
							alt="Google"
						/></a>
            <a href="#"><img
							className="h-7 w-7 rounded-full md:h-9 md:w-9 hover:scale-110 ease-in duration-200"
							src="/assets/icons/YouTube-icon-48.png"
							alt="Instagram"
						/></a>
					  </div>
          </div>
          </div>
          {/* Cards_9 end */}

        </div> 
        {/* Cards End */}
      </section>
    </>
  );
};

export default Clubs;
