import Head from "next/head";
import styles from "../../styles/Internship.module.css";

const Internships = () => {
	return (
		<>
			<Head>
				<title>Internships | Technical Council</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.root}>
				<h2 className={styles.title}>Coming Soon...</h2>
			</div>
		</>
	);
};

export default Internships;
