import Head from "next/head";
import styles from "../../styles/Clubs.module.css";

const About = () => {
	return (
		<>
			<Head>
				<title>About Us | Technical Council</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
};

export default About;
