import Head from "next/head";
import styles from "../../styles/Clubs.module.css";
import ABOUT from "../../src/Constants/about";

const About = () => {
  return (
    <>
      <Head>
        <title>About Us | Technical Council</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.root}>
				<h2 className={styles.title}>About Us</h2>
				<p className={styles.subtitle}>
        Technical Council IITGN is the student body that promotes and takes initiatives for the technical activities that happen at IIT Gandhinagar.
				</p>
				<div className={styles.clubsOuter}>
					{ABOUT.map((club) => {
						return (
							<div
								className={styles.clubCard}
								key={club.id}
								style={{
									backgroundColor: club.backgroundColor,
								}}
							>
								<div className={styles.bannerOuter}>
									<img
										className={styles.clubBanner}
										src={club.banner}
										style={{padding: "20px"}}
									/>
								</div>
								<div className={styles.clubInfo}>
									<h2 className={styles.clubName}>
										{club.name}
									</h2>
									<p className={styles.clubDesc}>
										{club.desc}
									</p>
								</div>
							</div>
						);
					})}
				</div>
			</div>
    </>
  );
};

export default About;
