import Head from "next/head";
import styles from "../../styles/Home.module.css";

const About = () => {
  return (
    <>
      <Head>
        <title>About Us | Technical Council</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-neutral-700  p-6 pt-20 lg:pb-20">
        <div className={styles.container}>
          <h1 className="text-center text-white text-4xl ">About Us</h1>
          <p className="pt-10 pb-5 text-center text-white text-lg leading-loose">Technical Council IITGN is the student body that promotes and takes initiatives for the technical activities that <br></br> happen at IIT Gandhinagar.
          </p>
        </div>

        
      {/* Cards */}
      <div class="grid grid-cols-1 lg:grid-cols-3 px-6 pt-20 lg:gap-x-8 lg:gap-y-4 justify-items-center">
          {/* Cards_1 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded max-w-sm">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4 ">
              <div class="text-green-700 text-xl mb-2">MISSION</div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            
          </div>
          </div>
          {/* Cards_1 end */}

          {/* Cards_2 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded max-w-sm">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4 ">
              <div class="text-green-700 text-xl mb-2">PLAN</div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            
          </div>
          </div>
          {/* Cards_2 end */}

          {/* Cards_3 */}
          <div class="py-10">
          <div class="max-w-sm rounded-lg border-red-700 border-2 bg-black overflow-hidden shadow-lg mx-1.5">
            <div class="bg-white rounded max-w-sm">
              <img class="w-full" src="https://picsum.photos/200" alt=""></img>
            </div>
            <div class="px-6 py-4 ">
              <div class="text-green-700 text-xl mb-2">VISION</div>
              <p class="text-white text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
              </p>
            </div>
            
          </div>
          </div>
          {/* Cards_3 end */}
        </div>
      </section>
    </>
  );
};

export default About;
